name: publish

on: [push]

jobs:
  publish-maintenance-page-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the maintain Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u hi-eu --password-stdin
        docker build . --tag ghcr.io/hi-eu/maintenance-page:latest
        docker push ghcr.io/hi-eu/maintenance-page:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
